apiVersion: core.choreo.dev/v1beta1
kind: Component
metadata:
  name: sns-mi-integration
  annotations:
    core.choreo.dev/component-type: mi
spec:
  type: MI
  endpoints:
    - name: sns-api
      port: 8290
      type: REST
      networkVisibilities:
        - Public
      context: /sns
